### PR TITLE
Rid prettier rule from test

### PR DESCRIPTION
**Pull request by 123aswin123**
This prettier rule is causing conflicts with the Linter, also I am going to add a separate auto prettier.

### CODE REVIEW

**Comment by Laksh47** [comment]
https://github.com/123aswin123/timebomb/blob/main/package.json#L38

Need to remove them from this packages.json file too? @123aswin123

**Comment by 123aswin123** [comment]
fair catch @Laksh47 suggest it as a change in the code itself!

**Comment by 123aswin123** [comment]
@Laksh47 This needs to be fixed, I shall do it tomorrow

**Comment by 123aswin123** [comment]
@Laksh47 can you please approve this?

**Pull request closed without merging**
